# site settings
title: Alaina Kwan
subtitle: UX/UI Portfolio
email: kwan.alaina@gmail.com
description: I'm a junior UX/UI designer.
baseurl: # the subpath of your site, e.g. /blog
url: https://alainakwan.com # the base hostname & protocol for your site
author: Alaina

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
github_url: https://github.com/alkwan
instagram_url: https://instagram.com/aeyeonarts
linkedin_url: https://www.linkedin.com/in/alaina-kwan/

# build settings
markdown: kramdown

sass:
  style: compressed
